name: 'Tests'
description: 'Runs the PHPUnit tests'

inputs:
  github_token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Install Dependencies'
      uses: netlogix/actions/.github/actions/composer-install@main
      with:
        php-version: '8.2'
        coverage: 'xdebug3'
        args: '--prefer-dist --no-progress --no-interaction --optimize-autoloader'
        github_token: ${{ inputs.github_token }}

    - name: 'Run Unit Tests'
      shell: bash
      env:
        XDEBUG_MODE: 'coverage'
      run: vendor/bin/phpunit --coverage-clover Build/Artifacts/Reports/Unit/clover.xml

    - name: 'Generate Unit Test Code Coverage Summary Report'
      uses: saschanowak/CloverCodeCoverageSummary@0.3.1
      with:
        filename: Build/Artifacts/Reports/Unit/clover.xml

    - name: 'Add Unit Test Code Coverage to file'
      shell: bash
      run: |
        echo '## Code Coverage Summery for unit tests' >> code-coverage-merged.md
        cat code-coverage-summary.md >> code-coverage-merged.md
        
        echo '## Code Coverage for unit tests' >> $GITHUB_STEP_SUMMARY
        cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
        cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY

    - name: 'Add Code Coverage as PR Comment'
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-merged.md
