name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-platform:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - uses: ./.github/actions/phpunit-test
        with:
          github_token: ${{ secrets.COMPOSER_AUTH }}
