name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-platform:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: 'xdebug3'

      - name: 'Validate composer.json and composer.lock'
        shell: bash
        run: composer validate

      - name: 'Install Composer Dependencies'
        shell: bash
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: 'Run Unit Tests'
        shell: bash
        env:
          XDEBUG_MODE: 'coverage'
        run: vendor/bin/phpunit tests/Unit
